name: Build OpenWrt APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison gawk gcc-multilib \
            gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip \
            zlib1g-dev file wget

      - name: Clone OpenWrt Snapshot (25.x, APK)
        run: |
          git clone --depth 1 https://git.openwrt.org/openwrt/openwrt.git openwrt
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install luci

      - name: Copy package
        run: |
          cp -r $GITHUB_WORKSPACE openwrt/package/luci-app-tvbox-agg

      - name: Config & build
        run: |
          cd openwrt
          echo "CONFIG_PACKAGE_luci-app-helloworld=m" > .config
          make defconfig
          make package/luci-app-helloworld/compile V=s -j$(nproc)

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-helloworld-apk
          path: openwrt/bin/packages/*/luci/luci-app-helloworld_*.apk